services:
  application:
    build: application/
    container_name: application
    depends_on:
      - database
      - liquibase
    environment:
      - HOST=database
    ports:
      - "9090:9090"
  database:
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres
    ports:
      - "5432:5432"
  gateway:
    build: gateway/
    container_name: gateway
    depends_on:
      - application
    ports:
      - "8080:8080"
    environment:
      - HOST=application
  liquibase:
    build: liquibase/
    container_name: liquibase
    depends_on:
      - database
    environment:
      - HOST=database
