--liquibase formatted sql

--changeset author:01-create-tables.sql

CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  TEXT                                    NOT NULL,
    email TEXT                                    NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT                                    NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT requests_pkey PRIMARY KEY (id),
    FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         TEXT                                    NOT NULL,
    description  TEXT                                    NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT,
    CONSTRAINT items_pkey PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status     TEXT                                    NOT NULL,
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      TEXT                                    NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

--rollback DROP TABLE comments;
--rollback DROP TABLE bookings;
--rollback DROP TABLE items;
--rollback DROP TABLE requests;
--rollback DROP TABLE users;
