--liquibase formatted sql

--changeset author:01-create-tables.sql

create table users (
     id    bigint generated by default as identity (start with 1) not null,
     name  varchar(32)                                            not null,
     email varchar(32)                                            not null,
     constraint users_pkey primary key (id),
     unique (email)
);

create table requests (
    id           bigint generated by default as identity (start with 1) not null,
    description  text                                                   not null,
    requester_id bigint                                                 not null,
    created      timestamp without time zone                            not null,
    constraint requests_pkey primary key (id),
    foreign key (requester_id) references users(id) on delete cascade
);

create table items (
     id           bigint generated by default as identity (start with 1) not null,
     name         varchar(32)                                            not null,
     description  text                                                   not null,
     is_available boolean                                                not null,
     owner_id     bigint                                                 not null,
     request_id   bigint,
     constraint items_pkey primary key (id),
     foreign key (owner_id) references users(id) on delete cascade,
     foreign key (request_id) references requests(id) on delete cascade
);

create table bookings (
    id         bigint generated by default as identity (start with 1) not null,
    start_date timestamp without time zone                            not null,
    end_date   timestamp without time zone                            not null,
    item_id    bigint                                                 not null,
    booker_id  bigint                                                 not null,
    status     varchar(32)                                            not null,
    constraint bookings_pkey primary key (id),
    foreign key (item_id) references items(id) on delete cascade,
    foreign key (booker_id) references users(id) on delete cascade
);

create table comments (
    id        bigint generated by default as identity (start with 1) not null,
    text      text                                                   not null,
    item_id   bigint                                                 not null,
    author_id bigint                                                 not null,
    created   timestamp without time zone                            not null,
    constraint comments_pkey primary key (id),
    foreign key (item_id) references items(id) on delete cascade,
    foreign key (author_id) references users(id) on delete cascade
);

--rollback drop table comments;
--rollback drop table bookings;
--rollback drop table items;
--rollback drop table requests;
--rollback drop table users;
