--liquibase formatted sql

--changeset author:Kozlov Nikita

CREATE TABLE IF NOT EXISTS users (
     PRIMARY KEY (id),
     id    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
     name  VARCHAR(255)                                           NOT NULL,
     email VARCHAR(255)                                           NOT NULL,
     UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    PRIMARY KEY (id),
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description  VARCHAR(255)                                           NOT NULL,
    requester_id BIGINT                                                 NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                            NOT NULL,
    FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
     PRIMARY KEY (id),
     id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
     name         VARCHAR(255)                                           NOT NULL,
     description  VARCHAR(255)                                           NOT NULL,
     is_available BOOLEAN                                                NOT NULL,
     owner_id     BIGINT                                                 NOT NULL,
     request_id   BIGINT,
     FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
     FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    PRIMARY KEY (id),
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE                            NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE                            NOT NULL,
    item_id    BIGINT                                                 NOT NULL,
    booker_id  BIGINT                                                 NOT NULL,
    status     VARCHAR(255)                                           NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    PRIMARY KEY (id),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    text      VARCHAR(255)                                    NOT NULL,
    item_id   BIGINT                                          NOT NULL,
    author_id BIGINT                                          NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE                     NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

--rollback drop table comments;
--rollback drop table bookings;
--rollback drop table items;
--rollback drop table requests;
--rollback drop table users;
